### ISSUE TITLE
Comparing without symbols

### ISSUE THREAD

**Issue by quasilyte** [tzneal/symSizeComp#2]
For binaries that have a lots of symbols, it's convenient to show only total size and sections diff instead of printing tons of lines for symbols.

There is `-pattern` option, but it does filters away sections as well.
It's possible to include all section names in pattern, but that's not very convenient.

Any thoughts about new flag that makes it possible to omit symbols comparison?
One way is to do it this way: `bincmp -no-symtab a b`.
Making symbol-specific regexp pattern seems to require more work.

**Comment by tzneal** [comment]
Is #3 what you were wanting?

**Comment by quasilyte** [comment]
@tzneal, yes. :)

**Comment by tzneal** [comment]
Great, thanks for the suggestion!
